name: todos_electrified
description: A todos ElectricSQL application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  drift: 2.16.0
  drift_postgres: ^1.1.0
  electricsql: 0.5.3
  electricsql_flutter: 0.5.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  logging: ^1.2.0
  path: ^1.8.2
  path_provider: ^2.1.1
  postgres: ^3.0.8
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: 2.4.0
  sqlite3_flutter_libs: 0.5.20

dev_dependencies:
  build_runner: ^2.4.4
  drift_dev: 2.16.0
  electricsql_cli: 0.5.5
  file: ^7.0.0 # Lowest version supported

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  platform: ^3.1.3 # Lowest version supported
  pub_semver: ^2.1.4 # Lowest version supported
  watcher: ^1.1.0 # Lowest version supported

flutter:
  uses-material-design: true

  assets:
    - assets/electric.svg
